name: Start Tutorial

on:
  workflow_dispatch:

jobs:
  start:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-start.yml@main
    with:
      tutorial-name: Security as Code
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
