name: Test Tutorial Integrity

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tutorial-tests:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-tutorial-tests.yml@main
    with:
      tutorial-name: Security as Code
      total-steps: 20
