name: Update From Template

on:
  workflow_dispatch:

jobs:
  update:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-update-from-template.yml@main
    with:
      tutorial-name: Security as Code
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
