name: Validate Progress

on:
  workflow_dispatch:

jobs:
  validate:
    uses: jgutierrezdtt/security-tutorial-base/.github/workflows/reusable-validate.yml@main
    with:
      tutorial-name: Security as Code
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
